[package]
name = "ros_macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0.86", features = ["full", "extra-traits"] }
proc-macro2 = "1.0.36"
quote = "1.0.14"
convert_case = "0.5.0"